### ISSUE TITLE
Adding menu bot Wiki (Japanese ver.)

### ISSUE THREAD

**Issue by ayaka528** [ryanvolum/menu-bot#17]
I translated menu bot Wiki for both Node and C# into Japanese.  Here is [the repo](https://github.com/ayaka528/menu-bot-wiki/commit/ea27af3af1af1c05a60153390fee854d6cd34d4c).

**Comment by ovishesh** [comment]
Updated with 日本語 content - https://github.com/ryanvolum/menu-bot/wiki
